# Generated by Django 5.0.4 on 2024-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id_aprendiz', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'aprendiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_aprendiz', models.IntegerField()),
                ('id_curso', models.IntegerField()),
                ('nota', models.IntegerField()),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('id_aprendiz', models.IntegerField()),
                ('curso', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
    ]
